- name: Packages required for VM management
  package:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - libguestfs-tools
      - python3-libvirt
      - python3-lxml
      - bridge-utils
      - cloud-image-utils
      - virtinst
  become: yes

- name: Libvirtd systemd service
  service:
    name: libvirtd
    enabled: true
    state: started

- name: Create default network
  community.libvirt.virt_net:
    command: define
    name: "{{ network_name }}"
    xml: "{{ lookup('template', 'vm-net-default.xml.j2') }}"

- name: Autostart default network
  community.libvirt.virt_net:
    autostart: yes
    name: "{{ network_name }}"

- name: "Start default network"
  community.libvirt.virt_net:
    state: active
    name: "{{ network_name }}"
