---
# OSM tile server VM
base_image_name: debian-11-genericcloud-amd64.qcow2
base_image_url: https://cloud.debian.org/images/cloud/bullseye/latest/{{ base_image_name }}
libvirt_pool_dir: "/var/lib/libvirt/images"
vm_net: default
vm_name: osmtileserver
vm_vcpus: 2
vm_ram_mb: 4096
vm_disk_size: 20G
cleanup_tmp: no
